# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10pU4i4QO52r3PvPYYio6eVZDq_DKdm75
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/drive/MyDrive/dataset/Video Games Sales.xlsx")
df.head()

df.shape

df.duplicated().sum()

df.isnull().sum()

df = df # give your dataframe name
missing_value= df.isnull().sum() 
percentage = (100 * df.isnull().sum() / len(df)).round(2).sort_values() 
data_types = df.dtypes
missing_values_table = pd.concat([missing_value, percentage, data_types], axis=1)
miss_val = missing_values_table.rename(columns = {0 : 'Missing Values',1 : 'Percentage',2 : 'Data Types'})
miss_vals=miss_val.sort_values(by='Percentage',ascending=False)
miss_vals1=miss_vals[miss_vals["Missing Values"]!=0]
# miss_vals1
miss_vals1.style.background_gradient(cmap='seismic')

df1 = df.dropna()
df1.shape

glob = df.sort_values(by=['Global'], ascending=False)
glob1=glob.head(1500)
glob.head(10)

review= df.sort_values(by=['Review'],ascending=False)
review1=review.head(1500)
review.head(10)

glob1.shape
glob1['Genre'].value_counts()

review1.shape
review1['Genre'].value_counts()

glob1_genre = glob1.head(1500)
glob1_genre['Platform'].value_counts()

review_genre = review1.head(1500)
review_genre.shape
review_genre['Platform'].value_counts()

review_genre = review1.head(1500)
review_genre.shape
review_genre['Publisher'].value_counts()

glob1_genre = glob1.head(1500)
glob1_genre['Publisher'].value_counts()

df['Genre'].value_counts()

"""2.  Amazon Prime Video Content"""

data = pd.read_excel('/content/drive/MyDrive/dataset/prime.xlsx')
data.head()

data.shape

data.duplicated().sum()

data.isnull().sum()

df = data # give your dataframe name
missing_value= df.isnull().sum() 
percentage = (100 * df.isnull().sum() / len(df)).round(2).sort_values() 
data_types = df.dtypes
missing_values_table = pd.concat([missing_value, percentage, data_types], axis=1)
miss_val = missing_values_table.rename(columns = {0 : 'Missing Values',1 : 'Percentage',2 : 'Data Types'})
miss_vals=miss_val.sort_values(by='Percentage',ascending=False)
miss_vals1=miss_vals[miss_vals["Missing Values"]!=0]
# miss_vals1
miss_vals1.style.background_gradient(cmap='seismic')

sns.countplot(x='type',data=data)

data['director'].unique()

data['director'].value_counts()

data['country'].unique()

data['country'].value_counts()

country_order = data['country'].value_counts().head(10).index
plt.figure(figsize=(9, 5))
sns.countplot(data=data, y='country', order=country_order)
plt.title('Top 10 country for watching ')
plt.xlabel('No. of views')
plt.ylabel(' country');

data['release_year'].unique()

data['release_year'].value_counts()

data['date_added'].unique()

#sns.countplot(x="country", hue="type", data=data)